In [34]:
import numpy as np

In [35]:
#create - from lists
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.dtype, arr.shape)

arr2 = np.array([1, 2, 3, 4, 5, "prime"])
print(arr2, type(arr2), arr2.dtype, arr2.shape)

arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(arr2D, arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (6,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)


In [36]:
# Properties
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [37]:
#Operations on arrays

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr, arr.shape)

reshaped =  arr.reshape((3, 2))
print(reshaped, reshaped.shape)

flattened = arr.flatten()  #2D => 1D
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [38]:
#Indexing
# arr = np.array([1, 2, 3, 4, 5])
arr = np.array([[1, 2, 3], [4, 5, 6]])


print(arr[1][1])
print(arr[0][2])

5
3


In [39]:
#Fancy Indexing
arr = np.array([1, 2, 3, 4, 5])

idx = [0, 1, 3]
print(arr[idx])

[1 2 4]


In [40]:
#Boolean Indexing
arr = np.array([1, 2, 3, 4, 5])

print(arr[arr > 2])
print(arr[arr % 2 == 0])
print(arr[arr % 2 != 0])

[3 4 5]
[2 4]
[1 3 5]


In [41]:
#Slicing
arr = np.array([1, 2, 3, 4, 5])

print(arr[1:4]) #[start, end, step
print(arr[1:])
print(arr[:4])
print(arr[:])
print(arr[::2])

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 2 3 4 5]
[1 3 5]


In [42]:
#Copy vs View
# nums = [1, 2, 3, 4, 5]
# sub_list = nums[1:3]
# print(sub_list)
# sub_list[0] = 200
# print(sub_list)
# print(nums)

arr = np.array([1, 2, 3, 4, 5])
sub_arr = arr[1:3].copy()
print(sub_arr)
sub_arr[0] = 200
print(sub_arr)
print(arr)

[2 3]
[200   3]
[1 2 3 4 5]


In [43]:
#Data Types

arr = np.array([1, 2, 3.14, 4, 5, "prime"])

print(arr, arr.dtype)

['1' '2' '3.14' '4' '5' 'prime'] <U32


In [44]:
arr1 = np.array([3 + 5j])
arr2 = np.array([2 + 3j])
print(arr1 + arr2, arr.dtype)
print(arr1 - arr2, arr.dtype)

[5.+8.j] <U32
[1.+2.j] <U32


In [45]:
arr = np.array(["prime", {1, 2, 3}, 3.14])
print(arr, arr.dtype)

['prime' {1, 2, 3} 3.14] object


In [46]:
# Multi-dimensional arrays

arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2D)

print(np.sum(arr2D))

sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

print(arr2D[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [54]:
#3D array

arr3D = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]])
print(arr3D, arr3D.shape)

#indexing
print(arr3D[1, 1, 0])

#slicing
print(arr3D[:, 0, :]) # first row from both layers
print(arr3D[:, :, 0]) # first col from both layers

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
9
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]


In [56]:
#vectorization

arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
print(arr ** 2)
print(arr + 2)
print(arr + arr2)

[ 1  4  9 16 25]
[3 4 5 6 7]
[ 7  9 11 13 15]


In [58]:
#broadcasting

arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])

print(arr.shape)
print(arr2.shape)
print(arr + arr2)

(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [62]:
#normalize

arr = np.array([[1, 2], [3, 4]])
mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr-mean)/std_dev
print(normalized_arr)

print(mean)
print(std_dev)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895


In [67]:
#Mathematical fnx

#aggregation

arr = np.array([1, 2, 3, 4, 5])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0


In [68]:
#power fnx

arr = np.array([1, 2, 3, 4, 5])
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr, 3))


[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [70]:
#log

arr = np.array([1, 2, 3, 4, 5])
print(np.log(arr))
print(np.log2(arr))


[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         1.         1.5849625  2.         2.32192809]


In [71]:
#rounding

print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.14))

3.0
4.0
3.0
3.0
